name = "sassy-cv"
compatibility_date = "2024-01-01"

[env.production]
name = "sassy-cv"

[env.staging] 
name = "sassy-cv-staging"

[[env.production.pages_build_output_dir]]
value = "out"

[[env.staging.pages_build_output_dir]]
value = "out"

# Secrets should be added via wrangler secret commands:
# wrangler secret put OPENAI_API_KEY --env production
# wrangler secret put GOOGLE_GENERATIVE_AI_API_KEY --env production
# wrangler secret put OPENAI_API_KEY --env staging  
# wrangler secret put GOOGLE_GENERATIVE_AI_API_KEY --env staging