name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CONVEX_URL: "https://example.com"
      NEXT_PUBLIC_PUBLIC_USER_ID: "public-cv-owner"
      NEXT_PUBLIC_DISABLE_AI: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run type-check

      - name: Build
        run: pnpm run build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Start app and run e2e tests
        run: |
          pnpm run start &
          npx wait-on http://localhost:3000
          pnpm run test:e2e
